import Head from "next/head";

export const metadata = {
    title: 'Check',
    description: 'Generated by create next app',
  }
  

const layout = ({ children }) => {
    return (
      <>
      {/* <Head>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css"  rel="stylesheet" />
      </Head> */}
      {children}
      {/* <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script> */}
      </>
    );
  };
  
  export default layout;