export const metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
  }
  

const layout = ({ children }) => {
    return (
      <>{children}</>
    );
  };
  
  export default layout;